### ISSUE TITLE
Off by one sample problems

### ISSUE THREAD

**Issue by pwarren** [pothosware/SoapyAudio#4]
During the development of the OpenRadio SDR[1] it was discovered that some sound cards present samples from one channel with a permanent delay of one sample, needs to be corrected for in sotware, see comments on [2].  

I know quisk uses the 'channel_delay' option to configure it, not sure where in quisk's source code it gets handled!

[1] http://openradio.net.au/index.php/OpenRadio_SDR
[2] https://ceworkbench.wordpress.com/2011/05/27/a-homebrew-soundcard-using-the-pcm2904/

**Comment by cjcliffe** [comment]
Hi @pwarren --  apologies as I meant to get this one fixed up sooner; but I think the latest commit to master should give you working -2...2 range sample offset adjustment (Which is actually just +2 I or +2 Q since it doesn't sample ahead).  

I've tested here by recording I/Q and playing back through an audio pipe after intentionally deleting a sample or two in one channel and was able to recover the stream with the offset.  Let me know if it works for you.

Cheers!

**Comment by pwarren** [comment]
Yep, works perfectly for my PCM2900 based sound card!  DSB reception unless I select -1 offset, thanks +1: 

Next I'll have to work out frequency control, I know we got the OpenSDR working with clicky click interface in Quisk, will have a dig!

**Comment by cjcliffe** [comment]
Sounds good; and thanks for the confirmation!
